service: ip-auth

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  environment:
    AUTHORIZER_ARN: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:provider.stage}-ip-auth-auth
    AUTH0_DOMAIN: ${file(../config.${self:provider.stage}.json):AUTH0_DOMAIN}
    AUTH0_CLIENT_ID: ${file(../config.${self:provider.stage}.json):AUTH0_CLIENT_ID}
  apiGateway:
    restApiId:
      Ref: ipWebapiApiGateway
    restApiResources:
      Fn::GetAtt:
        - ipWebapiApiGateway
        - RootResourceId

custom:
  pythonRequirements:
    noDeploy: []
    dockerizePip: true
    fileName: ../requirements.txt
    useDownloadCache: false
    useStaticCache: false

functions:
  auth:
    handler: auth.auth
    name: ${self:provider.stage}-${self:service}-auth
    cors: true

package:
  exclude:
    - ./**
  include:
    - auth.py
    - custom.yaml
    - package.json

resources:
  Resources:
    ipWebapiApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: IP-API-GATEWAY-${self:provider.stage}

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 0
        IdentitySource: method.request.header.X-Access-Token
        Name: ipAuthorizer
        RestApiId:
          Ref: ipWebapiApiGateway
        Type: TOKEN
        IdentityValidationExpression: '^[-0-9a-zA-z\.]*$'
        AuthorizerUri: arn:aws:apigateway:${self:provider.region}:lambda:path/2015-03-31/functions/${self:provider.environment.AUTHORIZER_ARN}/invocations
        AuthorizerCredentials:
          Fn::GetAtt:
            - ApiGatewayAuthorizerRole
            - Arn

    ApiGatewayAuthorizerRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service:
                  - 'apigateway.amazonaws.com'
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: 'InvokeAuthorizerFunction-${self:provider.stage}'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - lambda:InvokeAsync
                    - lambda:InvokeFunction
                  Resource: ${self:provider.environment.AUTHORIZER_ARN}

  # Api Gateway resources to make the API Base URL unchanging
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: ipWebapiApiGateway
      Export:
        Name: ip-${self:provider.stage}-ApiGateway-restApiId

    apiGatewayRestApiRootResourceId:
      Value:
          Fn::GetAtt:
          - ipWebapiApiGateway
          - RootResourceId
      Export:
        Name: ip-${self:provider.stage}-ApiGateway-rootResourceId

    apiGatewayAuthorizer:
      Value:
        Ref: ApiGatewayAuthorizer
      Export:
        Name: ip-${self:provider.stage}-ApiGateway-Authorizer


plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters